# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '<ProjectName>' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  # Rx
  pod 'RxSwift', '~> 6.2.0'
  pod 'RxCocoa', '~> 6.2.0'
  pod 'RxViewController', '~> 2.0.0'

  # Architecture
  pod 'ReactorKit', '~> 3.1.0'

  # Utils
  pod 'Then', '~> 2.7.0'
  pod 'SnapKit', '~> 5.0.1'

  # Network
  pod 'Moya/RxSwift', '~> 15.0.0'

  # Pods for your project

end
