# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

def services
  # Network
  pod 'Moya/RxSwift', '~> 15.0.0'

  # Utils
  pod 'Swinject', '~> 2.7'
  pod 'SwinjectAutoregistration', '~> 2.7'
end

def iOS
  # Rx
  pod 'RxSwift', '~> 6.2.0'
  pod 'RxCocoa', '~> 6.2.0'
  pod 'RxViewController', '~> 2.0.0'

  # Rx Framework
  pod 'ReactorKit', '~> 3.1.0'
  pod 'RxFlow', '~> 2.12.4'

  # Utils
  pod 'Then', '~> 2.7.0'
  pod 'SnapKit', '~> 5.0.1'
  pod 'Swinject', '~> 2.7'
  pod 'SwinjectAutoregistration', '~> 2.7'
end

def name
  '<name>'
end

workspace name

project 'iOS/' + name + '.xcodeproj'
project 'Service/Service.xcodeproj'

target name do
  project 'iOS/' + name
  iOS
end

target 'Service' do
  project 'Service/Service'
  services
end